set(__QT_DEPLOY_TARGET_spdlog_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/_deps/spdlog-build/MinSizeRel/spdlog.lib)
set(__QT_DEPLOY_TARGET_spdlog_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gtest_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/lib/MinSizeRel/gtest.lib)
set(__QT_DEPLOY_TARGET_gtest_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gtest_main_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/lib/MinSizeRel/gtest_main.lib)
set(__QT_DEPLOY_TARGET_gtest_main_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gmock_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/lib/MinSizeRel/gmock.lib)
set(__QT_DEPLOY_TARGET_gmock_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gmock_main_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/lib/MinSizeRel/gmock_main.lib)
set(__QT_DEPLOY_TARGET_gmock_main_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_core_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_core_tests.exe)
set(__QT_DEPLOY_TARGET_csx_core_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_core_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_csx_utils_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_utils_tests.exe)
set(__QT_DEPLOY_TARGET_csx_utils_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_utils_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_csx_camera_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_camera_tests.exe)
set(__QT_DEPLOY_TARGET_csx_camera_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_camera_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll)
set(__QT_DEPLOY_TARGET_csx_motion_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_motion_tests.exe)
set(__QT_DEPLOY_TARGET_csx_motion_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_motion_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll)
set(__QT_DEPLOY_TARGET_csx_tracking_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_tracking_tests.exe)
set(__QT_DEPLOY_TARGET_csx_tracking_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_tracking_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll)
set(__QT_DEPLOY_TARGET_csx_database_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_database_tests.exe)
set(__QT_DEPLOY_TARGET_csx_database_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_database_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_csx_recognition_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_recognition_tests.exe)
set(__QT_DEPLOY_TARGET_csx_recognition_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_recognition_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll)
set(__QT_DEPLOY_TARGET_csx_behavior_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_behavior_tests.exe)
set(__QT_DEPLOY_TARGET_csx_behavior_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_behavior_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll)
set(__QT_DEPLOY_TARGET_csx_threat_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_threat_tests.exe)
set(__QT_DEPLOY_TARGET_csx_threat_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_threat_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll)
set(__QT_DEPLOY_TARGET_csx_recording_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_recording_tests.exe)
set(__QT_DEPLOY_TARGET_csx_recording_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_recording_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll)
set(__QT_DEPLOY_TARGET_csx_hud_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/MinSizeRel/csx_hud_tests.exe)
set(__QT_DEPLOY_TARGET_csx_hud_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_hud_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll)
set(__QT_DEPLOY_TARGET_sqlite3_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/sqlite3.lib)
set(__QT_DEPLOY_TARGET_sqlite3_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_core_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_core.lib)
set(__QT_DEPLOY_TARGET_csx_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_utils_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_utils.lib)
set(__QT_DEPLOY_TARGET_csx_utils_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_camera_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_camera.lib)
set(__QT_DEPLOY_TARGET_csx_camera_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_motion_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_motion.lib)
set(__QT_DEPLOY_TARGET_csx_motion_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_tracking_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_tracking.lib)
set(__QT_DEPLOY_TARGET_csx_tracking_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_database_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_database.lib)
set(__QT_DEPLOY_TARGET_csx_database_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_recognition_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_recognition.lib)
set(__QT_DEPLOY_TARGET_csx_recognition_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_behavior_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_behavior.lib)
set(__QT_DEPLOY_TARGET_csx_behavior_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_threat_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_threat.lib)
set(__QT_DEPLOY_TARGET_csx_threat_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_recording_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_recording.lib)
set(__QT_DEPLOY_TARGET_csx_recording_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_hud_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_hud.lib)
set(__QT_DEPLOY_TARGET_csx_hud_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_radar_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_radar.lib)
set(__QT_DEPLOY_TARGET_csx_radar_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_voice_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_voice.lib)
set(__QT_DEPLOY_TARGET_csx_voice_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_alerts_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_alerts.lib)
set(__QT_DEPLOY_TARGET_csx_alerts_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_CyberSentinelX_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/CyberSentinelX.exe)
set(__QT_DEPLOY_TARGET_CyberSentinelX_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_CyberSentinelX_RUNTIME_DLLS C:/Qt/6.7.3/msvc2019_64/bin/Qt6QuickControls2.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Quick.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6QmlModels.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Qml.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Network.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6OpenGL.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Gui.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Core.dll)
set(__QT_DEPLOY_TARGET_csx_ui_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/MinSizeRel/csx_ui.lib)
set(__QT_DEPLOY_TARGET_csx_ui_TYPE STATIC_LIBRARY)
