set(__QT_DEPLOY_TARGET_spdlog_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/_deps/spdlog-build/Debug/spdlogd.lib)
set(__QT_DEPLOY_TARGET_spdlog_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gtest_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/lib/Debug/gtest.lib)
set(__QT_DEPLOY_TARGET_gtest_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gtest_main_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/lib/Debug/gtest_main.lib)
set(__QT_DEPLOY_TARGET_gtest_main_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gmock_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/lib/Debug/gmock.lib)
set(__QT_DEPLOY_TARGET_gmock_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_gmock_main_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/lib/Debug/gmock_main.lib)
set(__QT_DEPLOY_TARGET_gmock_main_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_core_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_core_tests.exe)
set(__QT_DEPLOY_TARGET_csx_core_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_core_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_csx_utils_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_utils_tests.exe)
set(__QT_DEPLOY_TARGET_csx_utils_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_utils_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_csx_camera_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_camera_tests.exe)
set(__QT_DEPLOY_TARGET_csx_camera_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_camera_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll)
set(__QT_DEPLOY_TARGET_csx_motion_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_motion_tests.exe)
set(__QT_DEPLOY_TARGET_csx_motion_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_motion_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll)
set(__QT_DEPLOY_TARGET_csx_tracking_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_tracking_tests.exe)
set(__QT_DEPLOY_TARGET_csx_tracking_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_tracking_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll)
set(__QT_DEPLOY_TARGET_csx_database_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_database_tests.exe)
set(__QT_DEPLOY_TARGET_csx_database_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_database_tests_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_csx_recognition_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_recognition_tests.exe)
set(__QT_DEPLOY_TARGET_csx_recognition_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_recognition_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll)
set(__QT_DEPLOY_TARGET_csx_behavior_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_behavior_tests.exe)
set(__QT_DEPLOY_TARGET_csx_behavior_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_behavior_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll)
set(__QT_DEPLOY_TARGET_csx_threat_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_threat_tests.exe)
set(__QT_DEPLOY_TARGET_csx_threat_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_threat_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll)
set(__QT_DEPLOY_TARGET_csx_recording_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_recording_tests.exe)
set(__QT_DEPLOY_TARGET_csx_recording_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_recording_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll)
set(__QT_DEPLOY_TARGET_csx_hud_tests_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/tests/Debug/csx_hud_tests.exe)
set(__QT_DEPLOY_TARGET_csx_hud_tests_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_csx_hud_tests_RUNTIME_DLLS C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll)
set(__QT_DEPLOY_TARGET_sqlite3_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/sqlite3.lib)
set(__QT_DEPLOY_TARGET_sqlite3_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_core_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_core.lib)
set(__QT_DEPLOY_TARGET_csx_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_utils_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_utils.lib)
set(__QT_DEPLOY_TARGET_csx_utils_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_camera_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_camera.lib)
set(__QT_DEPLOY_TARGET_csx_camera_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_motion_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_motion.lib)
set(__QT_DEPLOY_TARGET_csx_motion_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_tracking_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_tracking.lib)
set(__QT_DEPLOY_TARGET_csx_tracking_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_database_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_database.lib)
set(__QT_DEPLOY_TARGET_csx_database_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_recognition_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_recognition.lib)
set(__QT_DEPLOY_TARGET_csx_recognition_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_behavior_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_behavior.lib)
set(__QT_DEPLOY_TARGET_csx_behavior_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_threat_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_threat.lib)
set(__QT_DEPLOY_TARGET_csx_threat_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_recording_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_recording.lib)
set(__QT_DEPLOY_TARGET_csx_recording_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_hud_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_hud.lib)
set(__QT_DEPLOY_TARGET_csx_hud_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_radar_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_radar.lib)
set(__QT_DEPLOY_TARGET_csx_radar_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_voice_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_voice.lib)
set(__QT_DEPLOY_TARGET_csx_voice_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_csx_alerts_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_alerts.lib)
set(__QT_DEPLOY_TARGET_csx_alerts_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_CyberSentinelX_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/CyberSentinelX.exe)
set(__QT_DEPLOY_TARGET_CyberSentinelX_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_CyberSentinelX_RUNTIME_DLLS C:/Qt/6.7.3/msvc2019_64/bin/Qt6QuickControls2d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/opencv/build/opencv/build/x64/vc16/bin/opencv_world490d.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6QuickTemplates2d.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Quickd.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6OpenGLd.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6QmlModelsd.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Qmld.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Networkd.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Guid.dll;C:/Qt/6.7.3/msvc2019_64/bin/Qt6Cored.dll)
set(__QT_DEPLOY_TARGET_csx_ui_FILE D:/Edge AI Camera Monitor & Motion Security Guard/build-csx/Debug/csx_ui.lib)
set(__QT_DEPLOY_TARGET_csx_ui_TYPE STATIC_LIBRARY)
